name: ml4cvd
channels:
  - conda-forge
  - defaults
  - anaconda
dependencies:
  - python=3.6
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - matplotlib
  - seaborn
  - pre-commit
  - pylint
  - identify
  - setuptools
  - toml
  - black
  - isort
  - h5py
  - jupyterlab
  - ipyparallel
  - nodejs
  - pytest
  - numcodecs
  - tensorflow-gpu
  - tensorflow
  - pip
  - pip:
    - tensorflow-addons
    - tensorflow-probability
    - gitlint==0.13.1
