from ml4h.TensorMap import TensorMap, Interpretation

categorical_21_completeness_80 = TensorMap(
    'categorical_21_completeness_80', Interpretation.CATEGORICAL, shape=(21,), loss='mse', path_prefix='categorical',
    channel_map={
        'death': 0, 'Pacemaker_No_0_0': 1, 'Adopted-as-a-child_No_0_0': 2, 'Part-of-a-multiple-birth_No_0_0': 3,
        'Diabetes-diagnosed-by-doctor_No_0_0': 4, 'Alcohol-drinker-status_Current_0_0': 5,
        'Contraindications-for-spirometry_No_0_0': 6, 'Cancer-diagnosed-by-doctor_No_0_0': 7,
        'Used-an-inhaler-for-chest-within-last-hour_No_0_0': 8, 'Result-ranking_best_0_0': 9,
        'Type-of-accommodation-lived-in_A-house-or-bungalow_0_0': 10, 'Result-ranking_second-best_0_1': 11,
        'Caffeine-drink-within-last-hour_No_0_0': 12, 'Handedness-chiralitylaterality_Righthanded_0_0': 13,
        'Fracturedbroken-bones-in-last-5-years_No_0_0': 14, 'Current-tobacco-smoking_No_0_0': 15,
        'Wears-glasses-or-contact-lenses_Yes_0_0': 16, 'Ethnic-background_British_0_0': 17,
        'Other-eye-problems_No_0_0': 18, 'Chest-pain-or-discomfort_No_0_0': 19,
        'Smokingsmokers-in-household_No_0_0': 20,
    },
)

categorical_612_completeness_7 = TensorMap(
    'categorical_21_completeness_80', Interpretation.CATEGORICAL, shape=(612,), loss='mse', path_prefix='categorical',
    channel_map={
        'death': 0, 'Pacemaker_No_0_0': 1, 'Adopted-as-a-child_No_0_0': 2, 'Part-of-a-multiple-birth_No_0_0': 3,
        'Diabetes-diagnosed-by-doctor_No_0_0': 4, 'Alcohol-drinker-status_Current_0_0': 5,
        'Contraindications-for-spirometry_No_0_0': 6, 'Cancer-diagnosed-by-doctor_No_0_0': 7,
        'Used-an-inhaler-for-chest-within-last-hour_No_0_0': 8, 'Result-ranking_best_0_0': 9,
        'Type-of-accommodation-lived-in_A-house-or-bungalow_0_0': 10, 'Result-ranking_second-best_0_1': 11,
        'Caffeine-drink-within-last-hour_No_0_0': 12, 'Handedness-chiralitylaterality_Righthanded_0_0': 13,
        'Fracturedbroken-bones-in-last-5-years_No_0_0': 14, 'Current-tobacco-smoking_No_0_0': 15,
        'Wears-glasses-or-contact-lenses_Yes_0_0': 16, 'Ethnic-background_British_0_0': 17,
        'Other-eye-problems_No_0_0': 18, 'Chest-pain-or-discomfort_No_0_0': 19,
        'Smokingsmokers-in-household_No_0_0': 20, 'Falls-in-the-last-year_No-falls_0_0': 21,
        'Never-eat-eggs-dairy-wheat-sugar_I-eat-all-of-the-above_0_0': 22,
        'Country-of-birth-UKelsewhere_England_0_0': 23,
        'Types-of-transport-used-excluding-work_Carmotor-vehicle_0_0': 24,
        'Other-serious-medical-conditiondisability-diagnosed-by-doctor_No_0_0': 25,
        'Wheeze-or-whistling-in-the-chest-in-last-year_No_0_0': 26, 'Father-still-alive_No_0_0': 27,
        'Vascularheart-problems-diagnosed-by-doctor_None-of-the-above_0_0': 28, 'Hearing-difficultyproblems_No_0_0': 29,
        'Types-of-physical-activity-in-last-4-weeks_Walking-for-pleasure-not-as-a-means-of-transport_0_0': 30,
        'Ever-had-bowel-cancer-screening_No_0_0': 31, 'Result-ranking_third-best-ie-worst_0_2': 32,
        'Skin-colour_Fair_0_0': 33,
        'Blood-clot-DVT-bronchitis-emphysema-asthma-rhinitis-eczema-allergy-diagnosed-by-doctor_None-of-the-above_0_0': 34,
        'Hot-drink-temperature_Hot_0_0': 35, 'Vitamin-and-mineral-supplements_None-of-the-above_0_0': 36,
        'Facial-ageing_Younger-than-you-are_0_0': 37, 'Longstanding-illness-disability-or-infirmity_No_0_0': 38,
        'Major-dietary-changes-in-the-last-5-years_No_0_0': 39, 'Milk-type-used_Semiskimmed_0_0': 40,
        'Maternal-smoking-around-birth_No_0_0': 41, 'Illnesses-of-siblings_None-of-the-above-group-2_0_1': 42,
        'Hearing-difficultyproblems-with-background-noise_No_0_0': 43,
        'Mouthteeth-dental-problems_None-of-the-above_0_0': 44,
        'Current-employment-status_In-paid-employment-or-selfemployed_0_0': 45, 'Hearing-aid-user_No_0_0': 46,
        'Ever-smoked_Yes_0_0': 47, 'Mother-still-alive_No_0_0': 48, 'Variation-in-diet_Sometimes_0_0': 49,
        'Lambmutton-intake_Less-than-once-a-week_0_0': 50, 'Smoking-status_Never_0_0': 51,
        'Overall-health-rating_Good_0_0': 52, 'Mineral-and-other-dietary-supplements_None-of-the-above_0_0': 53,
        'Pork-intake_Less-than-once-a-week_0_0': 54, 'Salt-added-to-food_Neverrarely_0_0': 55,
        'Breastfed-as-a-baby_Yes_0_0': 56, 'Birth-weight-known_Yes-pounds-and-ounces_0_0': 57,
        'Illnesses-of-mother_None-of-the-above-group-2_0_1': 58, 'Usual-walking-pace_Steady-average-pace_0_0': 59,
        'Weight-change-compared-with-1-year-ago_No-weigh-about-the-same_0_0': 60, 'Sex_Female_0_0': 61,
        'Pregnant_No_0_0': 62, 'Bread-type_Wholemeal-or-wholegrain_0_0': 63,
        'Taking-other-prescription-medications_No_0_0': 64, 'Spread-type_Other-type-of-spreadmargarine_0_0': 65,
        'Ever-had-cervical-smear-test_Yes_0_0': 66,
        'Medication-for-pain-relief-constipation-heartburn_None-of-the-above_0_0': 67,
        'Comparative-height-size-at-age-10_About-average_0_0': 68,
        'Illnesses-of-father_None-of-the-above-group-2_0_1': 69,
        'Comparative-body-size-at-age-10_About-average_0_0': 70, 'Nonoily-fish-intake_Once-a-week_0_0': 71,
        'Own-or-rent-accommodation-lived-in_Own-outright-by-you-or-someone-in-your-household_0_0': 72,
        'Bilateral-oophorectomy-both-ovaries-removed_No_0_0': 73,
        'Taking-other-prescription-medications_Yes-you-will-be-asked-about-this-later-by-an-interviewer_0_0': 74,
        'Sex_Male_0_0': 75, 'Poultry-intake_24-times-a-week_0_0': 76, 'Beef-intake_Less-than-once-a-week_0_0': 77,
        'Illnesses-of-siblings_None-of-the-above-group-1_0_0': 78, 'FI1-numeric-addition-test_15_0_0': 79,
        'Cheese-intake_24-times-a-week_0_0': 80, 'Birth-weight-known_No_0_0': 81,
        'Ever-taken-oral-contraceptive-pill_Yes_0_0': 82, 'Coffee-type_Instant-coffee_0_0': 83,
        'Ever-had-hysterectomy-womb-removed_No_0_0': 84, 'Ever-had-breast-cancer-screening-mammogram_Yes_0_0': 85,
        'Alcohol-intake-versus-10-years-previously_Less-nowadays_0_0': 86,
        'Past-tobacco-smoking_I-have-never-smoked_0_0': 87, 'Ever-smoked_No_0_0': 88,
        'Drive-faster-than-motorway-speed-limit_Neverrarely_0_0': 89, 'Mother-still-alive_Yes_0_0': 90,
        'Own-or-rent-accommodation-lived-in_Own-with-a-mortgage_0_0': 91,
        'Hair-colour-natural-before-greying_Light-brown_0_0': 92, 'FI4-positional-arithmetic_6_0_0': 93,
        'Pain-types-experienced-in-last-month_None-of-the-above_0_0': 94,
        'Relative-age-voice-broke_About-average-age_0_0': 95,
        'Hearing-difficultyproblems-with-background-noise_Yes_0_0': 96,
        'Ease-of-skin-tanning_Get-moderately-tanned_0_0': 97, 'Usual-walking-pace_Brisk-pace_0_0': 98,
        'Medication-for-cholesterol-blood-pressure-diabetes-or-take-exogenous-hormones_None-of-the-above_0_0': 99,
        'hypertension': 100, 'Oily-fish-intake_Once-a-week_0_0': 101, 'Poultry-intake_Once-a-week_0_0': 102,
        'Types-of-physical-activity-in-last-4-weeks_Other-exercises-eg-swimming-cycling-keep-fit-bowling_0_1': 103,
        'Drive-faster-than-motorway-speed-limit_Sometimes_0_0': 104,
        'Frequency-of-stair-climbing-in-last-4-weeks_610-times-a-day_0_0': 105,
        'Use-of-sunuv-protection_Most-of-the-time_0_0': 106,
        'Ever-had-stillbirth-spontaneous-miscarriage-or-termination_No_0_0': 107,
        'Hair-colour-natural-before-greying_Dark-brown_0_0': 108,
        'Relative-age-of-first-facial-hair_About-average-age_0_0': 109,
        'Had-other-major-operations_Yes-you-will-be-asked-about-this-later-by-an-interviewer_0_0': 110,
        'Types-of-transport-used-excluding-work_Walk_0_1': 111,
        'Alcohol-intake-versus-10-years-previously_About-the-same_0_0': 112,
        'Spread-type_Butterspreadable-butter_0_0': 113, 'Variation-in-diet_Neverrarely_0_0': 114,
        'Alcohol-usually-taken-with-meals_Yes_0_0': 115, 'Qualifications_College-or-University-degree_0_0': 116,
        'Test-completion-status_complete_0_0': 117, 'Cochlear-implant_No_0_0': 118,
        'Stiffness-method_Direct-entry_0_0': 119, 'Oily-fish-intake_Less-than-once-a-week_0_0': 120,
        'Had-menopause_Yes_0_0': 121, 'Ever-used-hormonereplacement-therapy-HRT_No_0_0': 122,
        'Use-of-sunuv-protection_Sometimes_0_0': 123, 'Hearing-test-done_Yes_0_0': 124,
        'Current-employment-status_Retired_0_0': 125, 'Attempted-fluid-intelligence-FI-test_Begin-puzzles_0_0': 126,
        'Fractured-heel-right_no_0_0': 127, 'Fractured-heel-left_no_0_0': 128,
        'Comparative-body-size-at-age-10_Thinner_0_0': 129, 'Longstanding-illness-disability-or-infirmity_Yes_0_0': 130,
        'Heel-ultrasound-method-left_Direct-entry_0_0': 131, 'Completion-status-right_completed_0_0': 132,
        'Smoking-status_Previous_0_0': 133, 'Completion-status-left_completed_0_0': 134,
        'Heel-ultrasound-method-right_Direct-entry_0_0': 135, 'Ever-had-prostate-specific-antigen-PSA-test_No_0_0': 136,
        'PM-final-answer_Orange-circle_0_0': 137, 'Final-attempt-correct_yes_0_0': 138,
        'Beef-intake_Once-a-week_0_0': 139,
        'Medication-for-cholesterol-blood-pressure-or-diabetes_None-of-the-above_0_0': 140,
        'Mineral-and-other-dietary-supplements_Fish-oil-including-cod-liver-oil_0_0': 141,
        'Ever-had-bowel-cancer-screening_Yes_0_0': 142,
        'Weight-change-compared-with-1-year-ago_Yes-gained-weight_0_0': 143,
        'Processed-meat-intake_Less-than-once-a-week_0_0': 144, 'Triplet-correct-right_yes_0_1': 145,
        'Nonoily-fish-intake_Less-than-once-a-week_0_0': 146, 'Processed-meat-intake_Once-a-week_0_0': 147,
        'Had-major-operations_Yes-you-will-be-asked-about-this-later-by-an-interviewer_0_0': 148,
        'Loud-music-exposure-frequency_No_0_0': 149, 'Shortness-of-breath-walking-on-level-ground_No_0_0': 150,
        'Triplet-correct-left_yes_0_1': 151, 'Absence-of-notch-position-in-the-pulse-waveform_False_0_0': 152,
        'Alcohol-usually-taken-with-meals_It-varies_0_0': 153, 'Processed-meat-intake_24-times-a-week_0_0': 154,
        'Salt-added-to-food_Sometimes_0_0': 155,
        'Major-dietary-changes-in-the-last-5-years_Yes-because-of-other-reasons_0_0': 156,
        'Alcohol-intake-frequency_Once-or-twice-a-week_0_0': 157, 'Eye-problemsdisorders_None-of-the-above_0_0': 158,
        'Illnesses-of-mother_None-of-the-above-group-1_0_0': 159, 'Bread-type_White_0_0': 160,
        'Comparative-height-size-at-age-10_Taller_0_0': 161, 'Triplet-correct-right_yes_0_2': 162,
        'Duration-walking-for-pleasure_Between-30-minutes-and-1-hour_0_0': 163, 'Triplet-correct-left_yes_0_2': 164,
        'Prospective-memory-result_Correct-recall-on-first-attempt_0_0': 165,
        'PM-initial-answer_Orange-circle_0_0': 166, 'Noisy-workplace_No_0_0': 167, 'Leg-pain-on-walking_No_0_0': 168,
        'Hearing-difficultyproblems_Yes_0_0': 169, 'FI2-identify-largest-number_987_0_0': 170,
        'Maternal-smoking-around-birth_Yes_0_0': 171, 'Breastfed-as-a-baby_Do-not-know_0_0': 172,
        'Father-still-alive_Yes_0_0': 173, 'Average-total-household-income-before-tax_31000-to-51999_0_0': 174,
        'Tinnitus_No-never_0_0': 175, 'Both-eyes-present_Yes_0_0': 176,
        'Visual-acuity-measured-right_Measurable_0_0': 177,
        'Vascularheart-problems-diagnosed-by-doctor_High-blood-pressure_0_0': 178,
        'Visual-acuity-measured-left_Measurable_0_0': 179, 'Direct-or-mirror-view-right_plain_0_0': 180,
        'Direct-or-mirror-view-left_plain_0_0': 181, 'Current-eye-infection_No_0_0': 182,
        'Types-of-physical-activity-in-last-4-weeks_Light-DIY-eg-pruning-watering-the-lawn_0_1': 183,
        'Pork-intake_Once-a-week_0_0': 184, 'Worked-with-pesticides_Rarelynever_0_0': 185,
        'Overall-health-rating_Fair_0_0': 186, 'Illnesses-of-father_None-of-the-above-group-1_0_0': 187,
        'Breathing-problems-during-period-of-job_No_0_0': 188, 'Autorefraction-method-right_Measurable_0_0': 189,
        'Illnesses-of-mother_High-blood-pressure_0_0': 190, 'Autorefraction-method-left_Measurable_0_0': 191,
        'Past-tobacco-smoking_Smoked-on-most-or-all-days_0_0': 192, 'Lambmutton-intake_Once-a-week_0_0': 193,
        'osteoarthritis': 194, 'Alcohol-intake-frequency_Daily-or-almost-daily_0_0': 195,
        'Intraocular-pressure-IOP-method-right_Measurable_0_0': 196, 'Milk-type-used_Skimmed_0_0': 197,
        'Noncancer-illness-code-selfreported_hypertension_0_0': 198, 'Ever-had-eye-surgery_No_0_0': 199,
        'Facial-ageing_About-your-age_0_0': 200, 'Intraocular-pressure-IOP-method-left_Measurable_0_0': 201,
        'Nonaccidental-death-in-close-genetic-family_No_0_0': 202,
        'Ease-of-skin-tanning_Get-mildly-or-occasionally-tanned_0_0': 203,
        'Cereal-type_Oat-cereal-eg-Ready-Brek-porridge_0_0': 204,
        'Alcohol-intake-frequency_Three-or-four-times-a-week_0_0': 205,
        'Average-total-household-income-before-tax_18000-to-30999_0_0': 206, 'Cheese-intake_Once-a-week_0_0': 207,
        'Qualifications_O-levelsGCSEs-or-equivalent_0_0': 208, 'Breastfed-as-a-baby_No_0_0': 209,
        'Ever-used-hormonereplacement-therapy-HRT_Yes_0_0': 210,
        'Pain-types-experienced-in-last-month_Headache_0_0': 211, 'hypercholesterolemia': 212,
        'Workplace-had-a-lot-of-diesel-exhaust_Rarelynever_0_0': 213,
        'Frequency-of-walking-for-pleasure-in-last-4-weeks_23-times-in-the-last-4-weeks_0_0': 214,
        'Frequency-of-stair-climbing-in-last-4-weeks_15-times-a-day_0_0': 215,
        'Wheeze-or-whistling-in-the-chest-in-last-year_Yes_0_0': 216, 'Ease-of-skin-tanning_Get-very-tanned_0_0': 217,
        'FI3-word-interpolation_adult_0_0': 218, 'Comparative-height-size-at-age-10_Shorter_0_0': 219,
        'Other-serious-medical-conditiondisability-diagnosed-by-doctor_Yes-you-will-be-asked-about-this-later-by-an-interviewer_0_0': 220,
        'Worked-with-paints-thinners-or-glues_Rarelynever_0_0': 221, 'Job-involved-shift-work_No_0_0': 222,
        'Duration-of-other-exercises_Between-30-minutes-and-1-hour_0_0': 223, 'Use-of-sunuv-protection_Always_0_0': 224,
        'Type-of-tobacco-previously-smoked_Manufactured-cigarettes_0_0': 225, 'Back-pain-for-3-months_Yes_0_0': 226,
        'Reason-for-reducing-amount-of-alcohol-drunk_Other-reason_0_0': 227, 'Triplet-correct-right_yes_0_3': 228,
        'Frequency-of-stair-climbing-in-last-4-weeks_1115-times-a-day_0_0': 229,
        'Workplace-full-of-chemical-or-other-fumes_Rarelynever_0_0': 230, 'Skin-colour_Light-olive_0_0': 231,
        'Likelihood-of-resuming-smoking_No-definitely-not_0_0': 232,
        'Worked-with-materials-containing-asbestos_Rarelynever_0_0': 233,
        'Nonbutter-spread-type-details_Polyunsaturatedsunflower-oil-based-spread-eg-Flora_0_0': 234,
        'Triplet-correct-left_yes_0_3': 235, 'anycancer': 236,
        'Types-of-physical-activity-in-last-4-weeks_Light-DIY-eg-pruning-watering-the-lawn_0_2': 237,
        'Blood-clot-DVT-bronchitis-emphysema-asthma-rhinitis-eczema-allergy-diagnosed-by-doctor_Hayfever-allergic-rhinitis-or-eczema_0_0': 238,
        'Had-other-major-operations_No_0_0': 239, 'Average-total-household-income-before-tax_Less-than-18000_0_0': 240,
        'Average-total-household-income-before-tax_52000-to-100000_0_0': 241,
        'Ease-of-skin-tanning_Never-tan-only-burn_0_0': 242, 'Triplet-correct-left_yes_0_5': 243,
        'Types-of-physical-activity-in-last-4-weeks_Heavy-DIY-eg-weeding-lawn-mowing-carpentry-digging_0_2': 244,
        'Triplet-correct-left_yes_0_6': 245, 'Triplet-correct-right_yes_0_8': 246,
        'Qualifications_None-of-the-above_0_0': 247, 'Workplace-very-dusty_Rarelynever_0_0': 248,
        'Coffee-type_Ground-coffee-include-espresso-filter-etc_0_0': 249, 'Triplet-correct-left_yes_0_7': 250,
        'Hot-drink-temperature_Very-hot_0_0': 251, 'Triplet-correct-right_yes_0_6': 252,
        'Cheese-intake_Less-than-once-a-week_0_0': 253, 'Pork-intake_Never_0_0': 254,
        'Lambmutton-intake_Never_0_0': 255, 'FI7-synonym_cease_0_0': 256, 'Triplet-correct-right_yes_0_11': 257,
        'Breathing-problems-during-period-of-job_No_0_1': 258, 'Knee-pain-for-3-months_Yes_0_0': 259,
        'Ever-had-stillbirth-spontaneous-miscarriage-or-termination_Yes_0_0': 260,
        'Worked-with-pesticides_Rarelynever_0_1': 261, 'Triplet-correct-right_no_0_4': 262,
        'Frequency-of-other-exercises-in-last-4-weeks_23-times-a-week_0_0': 263,
        'Cereal-type_Other-eg-Cornflakes-Frosties_0_0': 264, 'Triplet-correct-left_yes_0_9': 265,
        'Vitamin-and-mineral-supplements_Multivitamins-minerals_0_0': 266, 'Triplet-correct-left_yes_0_10': 267,
        'Triplet-correct-left_yes_0_8': 268, 'Oily-fish-intake_24-times-a-week_0_0': 269,
        'Had-major-operations_No_0_0': 270, 'Alcohol-usually-taken-with-meals_No_0_0': 271,
        'Triplet-correct-left_no_0_4': 272, 'Neckshoulder-pain-for-3-months_Yes_0_0': 273,
        'Triplet-correct-right_yes_0_12': 274, 'Cereal-type_Muesli_0_0': 275, 'Triplet-correct-left_yes_0_13': 276,
        'Triplet-correct-left_yes_0_11': 277, 'Triplet-correct-left_yes_0_14': 278,
        'Triplet-correct-right_yes_0_7': 279, 'Duration-of-light-DIY_Between-30-minutes-and-1-hour_0_0': 280,
        'Triplet-correct-right_yes_0_13': 281, 'Triplet-correct-right_yes_0_10': 282,
        'FI6-conditional-arithmetic_69_0_0': 283, 'Workplace-very-cold_Rarelynever_0_0': 284,
        'Triplet-correct-right_yes_0_9': 285, 'Triplet-correct-left_no_0_12': 286, 'Triplet-correct-left_yes_0_15': 287,
        'Triplet-correct-right_no_0_5': 288, 'Triplet-correct-right_yes_0_15': 289,
        'Triplet-correct-right_yes_0_5': 290, 'Triplet-correct-right_yes_0_14': 291,
        'Overall-health-rating_Excellent_0_0': 292, 'Triplet-correct-right_no_0_14': 293,
        'Triplet-correct-right_no_0_15': 294, 'Triplet-correct-left_yes_0_12': 295, 'Triplet-correct-left_no_0_15': 296,
        'Triplet-correct-right_no_0_9': 297, 'Triplet-correct-right_no_0_10': 298, 'Triplet-correct-right_no_0_7': 299,
        'Triplet-correct-right_no_0_13': 300, 'Qualifications_A-levelsAS-levels-or-equivalent_0_1': 301, 'hernia': 302,
        'Chest-pain-felt-outside-physical-activity_No_0_0': 303, 'Triplet-correct-left_no_0_11': 304,
        'composite_mi_cad_stroke_death': 305, 'Comparative-body-size-at-age-10_Plumper_0_0': 306,
        'Triplet-correct-left_no_0_14': 307, 'Job-involved-shift-work_No_0_1': 308,
        'Chest-pain-or-discomfort_Yes_0_0': 309, 'Triplet-correct-left_yes_0_4': 310,
        'Triplet-correct-left_no_0_13': 311, 'composite_mi_cad_stroke_death_exclude_aml': 312,
        'Workplace-had-a-lot-of-diesel-exhaust_Rarelynever_0_1': 313,
        'Doctor-restricts-physical-activity-due-to-heart-condition_No_0_0': 314, 'Triplet-correct-right_no_0_12': 315,
        'Pain-types-experienced-in-last-month_Neck-or-shoulder-pain_0_0': 316,
        'Alcohol-intake-versus-10-years-previously_More-nowadays_0_0': 317,
        'composite_mi_cad_stroke_death_exclude_heme': 318,
        'Frequency-of-walking-for-pleasure-in-last-4-weeks_23-times-a-week_0_0': 319,
        'Triplet-correct-left_no_0_8': 320, 'Triplet-correct-left_no_0_10': 321,
        'Chest-pain-felt-during-physical-activity_No_0_0': 322,
        'Duration-walking-for-pleasure_Between-15-and-30-minutes_0_0': 323, 'Triplet-correct-right_yes_0_4': 324,
        'Triplet-correct-left_no_0_9': 325, 'Able-to-walk-or-cycle-unaided-for-10-minutes_Yes_0_0': 326,
        'Worked-with-paints-thinners-or-glues_Rarelynever_0_1': 327,
        'Past-tobacco-smoking_Just-tried-once-or-twice_0_0': 328, 'Completion-status-of-test_Fully-completed_0_0': 329,
        'Hairbalding-pattern_Pattern-1_0_0': 330, 'Hot-drink-temperature_Warm_0_0': 331,
        'Triplet-correct-right_no_0_11': 332, 'Light-smokers-at-least-100-smokes-in-lifetime_No_0_0': 333,
        'Qualifications_O-levelsGCSEs-or-equivalent_0_2': 334, 'asthma': 335, 'Triplet-correct-right_no_0_6': 336,
        'Triplet-correct-left_no_0_7': 337, 'Cereal-type_Biscuit-cereal-eg-Weetabix_0_0': 338,
        'Coffee-type_Decaffeinated-coffee-any-type_0_0': 339,
        'Types-of-transport-used-excluding-work_Public-transport_0_2': 340,
        'Nonoily-fish-intake_24-times-a-week_0_0': 341,
        'Worked-with-materials-containing-asbestos_Rarelynever_0_1': 342,
        'Workplace-full-of-chemical-or-other-fumes_Rarelynever_0_1': 343, 'Triplet-correct-left_no_0_6': 344,
        'Target-heart-rate-achieved_False_0_0': 345, 'Triplet-correct-right_no_0_8': 346,
        'Triplet-correct-left_no_0_5': 347, 'Weight-change-compared-with-1-year-ago_Yes-lost-weight_0_0': 348,
        'Medication-for-pain-relief-constipation-heartburn_Aspirin_0_0': 349, 'Other-eye-problems_Yes_0_0': 350,
        'Never-eat-eggs-dairy-wheat-sugar_Sugar-or-foodsdrinks-containing-sugar_0_0': 351,
        'ECGbike-method-for-fitness-test_Bicycle_0_0': 352, 'Triplet-correct-left_no_0_3': 353,
        'Illnesses-of-father_High-blood-pressure_0_0': 354, 'OCT-measured-right_Measurable_0_0': 355,
        'Cereal-type_Bran-cereal-eg-All-Bran-Branflakes_0_0': 356, 'imaging': 357,
        'Falls-in-the-last-year_Only-one-fall_0_0': 358,
        'Medication-for-pain-relief-constipation-heartburn_Paracetamol_0_0': 359,
        'Medication-for-pain-relief-constipation-heartburn_Ibuprofen-eg-Nurofen_0_0': 360,
        'FI5-family-relationship-calculation_cousin_0_0': 361, 'OCT-measured-left_Measurable_0_0': 362,
        'Frequency-of-light-DIY-in-last-4-weeks_23-times-in-the-last-4-weeks_0_0': 363,
        'Worked-with-pesticides_Rarelynever_0_2': 364, 'Types-of-transport-used-excluding-work_Walk_0_0': 365,
        'Illnesses-of-siblings_High-blood-pressure_0_0': 366, 'Triplet-correct-right_no_0_3': 367,
        'Breathing-problems-during-period-of-job_No_0_2': 368, 'Menstruating-today_No_0_0': 369,
        'Past-tobacco-smoking_Smoked-occasionally_0_0': 370, 'Workplace-very-dusty_Rarelynever_0_1': 371,
        'Nonbutter-spread-type-details_Olive-oil-based-spread-eg-Bertolli_0_0': 372, 'Had-menopause_No_0_0': 373,
        'Workplace-very-hot_Rarelynever_0_0': 374, 'FI8-chained-arithmetic_26_0_0': 375,
        'Frequency-of-light-DIY-in-last-4-weeks_23-times-a-week_0_0': 376, 'Illnesses-of-father_Heart-disease_0_0': 377,
        'Workplace-very-noisy_Rarelynever_0_0': 378, 'composite_mi_cad_stroke_hf': 379,
        'Worked-with-paints-thinners-or-glues_Rarelynever_0_2': 380,
        'Chest-pain-or-discomfort-walking-normally_No_0_0': 381, 'Volume-level-set-by-participant-left_10_0_0': 382,
        'Job-involved-shift-work_No_0_2': 383, 'Frequency-of-walking-for-pleasure-in-last-4-weeks_Once-a-week_0_0': 384,
        'Ever-had-prostate-specific-antigen-PSA-test_Yes_0_0': 385, 'gastroesophageal_reflux_disease': 386,
        'Light-smokers-at-least-100-smokes-in-lifetime_Yes_0_0': 387,
        'Reason-for-reducing-amount-of-alcohol-drunk_Health-precaution_0_0': 388,
        'Pain-types-experienced-in-last-month_Back-pain_0_0': 389,
        'Workplace-had-a-lot-of-diesel-exhaust_Rarelynever_0_2': 390, 'Salt-added-to-food_Usually_0_0': 391,
        'Illnesses-of-mother_None-of-the-above-group-2_0_2': 392, 'Volume-level-set-by-participant-right_10_0_0': 393,
        'Bread-type_Brown_0_0': 394, 'Maternal-smoking-around-birth_Do-not-know_0_0': 395,
        'Types-of-physical-activity-in-last-4-weeks_Other-exercises-eg-swimming-cycling-keep-fit-bowling_0_0': 396,
        'Mouthteeth-dental-problems_Dentures_0_0': 397,
        'Workplace-full-of-chemical-or-other-fumes_Rarelynever_0_2': 398,
        'Frequency-of-heavy-DIY-in-last-4-weeks_23-times-in-the-last-4-weeks_0_0': 399,
        'Program-category_Category-1-cycle-rising-to-50-level_0_0': 400, 'Oily-fish-intake_Never_0_0': 401,
        'Hairbalding-pattern_Pattern-3_0_0': 402, 'Wears-glasses-or-contact-lenses_No_0_0': 403,
        'composite_mi_cad_stroke': 404, 'Ever-stopped-smoking-for-6-months_No_0_0': 405,
        'Beef-intake_24-times-a-week_0_0': 406, 'composite_mi_cad_stroke_exclude_heme': 407,
        'Duration-of-light-DIY_Between-15-and-30-minutes_0_0': 408, 'coronary_artery_disease_soft': 409,
        'Mineral-and-other-dietary-supplements_Glucosamine_0_1': 410,
        'Worked-with-materials-containing-asbestos_Rarelynever_0_2': 411,
        'Alcohol-intake-frequency_Special-occasions-only_0_0': 412,
        'Workplace-had-a-lot-of-cigarette-smoke-from-other-people-smoking_Rarelynever_0_0': 413,
        'Why-stopped-smoking_Health-precaution_0_0': 414,
        'Alcohol-intake-frequency_One-to-three-times-a-month_0_0': 415, 'Workplace-very-cold_Rarelynever_0_1': 416,
        'Smoking-status_Current_0_0': 417, 'composite_mi_cad_stroke_death_exclude_anycancer': 418,
        'Duration-walking-for-pleasure_Between-1-and-15-hours_0_0': 419,
        'Illnesses-of-father_None-of-the-above-group-2_0_2': 420, 'diverticular_disease': 421,
        'Workplace-had-a-lot-of-cigarette-smoke-from-other-people-smoking_Rarelynever_0_1': 422,
        'Workplace-very-dusty_Rarelynever_0_2': 423, 'Poultry-intake_Less-than-once-a-week_0_0': 424,
        'Mouthteeth-dental-problems_Bleeding-gums_0_0': 425, 'Headaches-for-3-months_No_0_0': 426,
        'Beef-intake_Never_0_0': 427, 'cataract': 428,
        'Blood-clot-DVT-bronchitis-emphysema-asthma-rhinitis-eczema-allergy-diagnosed-by-doctor_Asthma_0_0': 429,
        'Frequency-of-light-DIY-in-last-4-weeks_Once-a-week_0_0': 430,
        'Ever-had-breast-cancer-screening-mammogram_No_0_0': 431,
        'Qualifications_A-levelsAS-levels-or-equivalent_0_0': 432, 'Spread-type_Neverrarely-use-spread_0_0': 433,
        'Hair-colour-natural-before-greying_Blonde_0_0': 434, 'Illnesses-of-mother_None-of-the-above-group-1_0_1': 435,
        'Illnesses-of-father_None-of-the-above-group-1_0_1': 436, 'coronary_artery_disease_intermediate': 437,
        'Duration-of-other-exercises_Between-1-and-15-hours_0_0': 438, 'Operation-code_hysterectomy_0_0': 439,
        'Work-hours-lumped-category_30-to-40-hours_0_0': 440,
        'Frequency-of-heavy-DIY-in-last-4-weeks_Once-a-week_0_0': 441,
        'Types-of-physical-activity-in-last-4-weeks_Heavy-DIY-eg-weeding-lawn-mowing-carpentry-digging_0_3': 442,
        'Treatmentmedication-code_aspirin_0_0': 443,
        'Medication-for-cholesterol-blood-pressure-or-diabetes_Cholesterol-lowering-medication_0_0': 444,
        'Fracturedbroken-bones-in-last-5-years_Yes_0_0': 445, 'composite_mi_death': 446,
        'Duration-of-heavy-DIY_Between-30-minutes-and-1-hour_0_0': 447, 'Use-of-sunuv-protection_Neverrarely_0_0': 448,
        'Hairbalding-pattern_Pattern-2_0_0': 449, 'composite_af_chf_dcm_death': 450,
        'Workplace-very-hot_Rarelynever_0_1': 451,
        'Average-total-household-income-before-tax_Prefer-not-to-answer_0_0': 452,
        'Types-of-transport-used-excluding-work_Public-transport_0_1': 453, 'Workplace-very-noisy_Rarelynever_0_1': 454,
        'Pain-types-experienced-in-last-month_Back-pain_0_1': 455, 'Ever-taken-oral-contraceptive-pill_No_0_0': 456,
        'Ever-stopped-smoking-for-6-months_Yes_0_0': 457, 'Believed-safe-to-perform-DXA-scan_Yes_2_0': 458,
        'Cochlear-implant_No_2_0': 459,
        'Workplace-had-a-lot-of-cigarette-smoke-from-other-people-smoking_Rarelynever_0_2': 460,
        'Nonaccidental-death-in-close-genetic-family_Yes_0_0': 461,
        'Types-of-physical-activity-in-last-4-weeks_Heavy-DIY-eg-weeding-lawn-mowing-carpentry-digging_0_1': 462,
        'Frequency-of-other-exercises-in-last-4-weeks_Once-a-week_0_0': 463, 'Adopted-as-a-child_No_2_0': 464,
        'Volume-level-set-by-participant-right_20_0_0': 465, 'Hearing-test-done_Yes_2_0': 466,
        'Believed-safe-to-perform-brain-MRI-scan_Yes_2_0': 467,
        'Believed-safe-to-perform-abdominal-MRI-scan_Yes_2_0': 468, 'Volume-level-set-by-participant-left_20_0_0': 469,
        'Current-tobacco-smoking_No_2_0': 470, 'Processed-meat-intake_Never_0_0': 471,
        'Illnesses-of-father_Heart-disease_0_1': 472,
        'Major-dietary-changes-in-the-last-5-years_Yes-because-of-illness_0_0': 473, 'Pacemaker_No_2_0': 474,
        'Workplace-very-cold_Rarelynever_0_2': 475, 'Hair-colour-natural-before-greying_Black_0_0': 476,
        'Brain-MRI-measuring-method_Direct-entry_2_0': 477, 'Abdominal-MRI-measuring-method_Direct-entry_2_0': 478,
        'DXA-measuring-method_Direct-entry_2_0': 479, 'Handedness-chiralitylaterality_Lefthanded_0_0': 480,
        'Completion-status-of-numeric-memory-test_stopped_0_0': 481,
        'Drive-faster-than-motorway-speed-limit_Often_0_0': 482, 'Completion-status-left_completed_2_0': 483,
        'Chest-pain-or-discomfort-when-walking-uphill-or-hurrying_No_0_0': 484,
        'Completion-status-right_completed_2_0': 485, 'Type-of-accommodation-lived-in_A-house-or-bungalow_2_0': 486,
        'Diabetes-diagnosed-by-doctor_No_2_0': 487, 'Headaches-for-3-months_Yes_0_0': 488,
        'Qualifications_O-levelsGCSEs-or-equivalent_0_1': 489, 'Digits-entered-correctly_yes_0_1': 490,
        'Reason-for-glassescontact-lenses_For-shortsightedness-ie-only-or-mainly-for-distance-viewing-such-as-driving-cinema-etc-called-myopia_0_0': 491,
        'Wears-glasses-or-contact-lenses_Yes_2_0': 492,
        'Type-of-accommodation-lived-in_A-flat-maisonette-or-apartment_0_0': 493,
        'Workplace-had-a-lot-of-cigarette-smoke-from-other-people-smoking_Sometimes_0_0': 494,
        'Test-completion-status_complete_2_0': 495, 'Smoked-cigarette-or-pipe-within-last-hour_No_0_0': 496,
        'Hearing-aid-user_No_2_0': 497, 'Workplace-very-hot_Sometimes_0_0': 498,
        'Alcohol-drinker-status_Current_2_0': 499, 'Facial-ageing_Do-not-know_0_0': 500,
        'Chest-pain-or-discomfort_No_2_0': 501, 'Attempted-fluid-intelligence-FI-test_Begin-puzzles_2_0': 502,
        'Breathing-problems-during-period-of-job_No_0_3': 503,
        'Medication-for-pain-relief-constipation-heartburn_Paracetamol_0_1': 504,
        'Smokingsmokers-in-household_No_2_0': 505, 'Shortness-of-breath-walking-on-level-ground_No_2_0': 506,
        'depression': 507, 'Worked-with-pesticides_Rarelynever_0_3': 508, 'Digits-entered-correctly_yes_0_0': 509,
        'Triplet-correct-right_yes_2_1': 510,
        'Frequency-of-other-exercises-in-last-4-weeks_23-times-in-the-last-4-weeks_0_0': 511,
        'PM-final-answer_Orange-circle_2_0': 512, 'Final-attempt-correct_yes_2_0': 513,
        'DXA-measurement-completed_Yes_2_0': 514, 'Workplace-very-hot_Rarelynever_0_2': 515,
        'Digits-entered-correctly_yes_0_2': 516, 'Loud-music-exposure-frequency_No_2_0': 517,
        'Fracturedbroken-bones-in-last-5-years_No_2_0': 518,
        'Qualifications_Other-professional-qualifications-eg-nursing-teaching_0_3': 519,
        'Contraindications-for-spirometry_No_2_0': 520,
        'Frequency-of-heavy-DIY-in-last-4-weeks_Once-in-the-last-4-weeks_0_0': 521,
        'Workplace-very-noisy_Rarelynever_0_2': 522, 'Used-an-inhaler-for-chest-within-last-hour_No_2_0': 523,
        'Triplet-correct-left_yes_2_1': 524, 'Frequency-of-walking-for-pleasure-in-last-4-weeks_Every-day_0_0': 525,
        'FI1-numeric-addition-test_15_2_0': 526, 'Hip-pain-for-3-months_Yes_0_0': 527,
        'Workplace-had-a-lot-of-diesel-exhaust_Rarelynever_0_3': 528, 'Job-involved-shift-work_No_0_3': 529,
        'Mouthteeth-dental-problems_Mouth-ulcers_0_0': 530, 'Hairbalding-pattern_Pattern-4_0_0': 531,
        'Illnesses-of-mother_Diabetes_0_0': 532, 'Result-ranking_second-best_2_1': 533, 'Result-ranking_best_2_0': 534,
        'Worked-with-paints-thinners-or-glues_Rarelynever_0_3': 535, 'Cancer-diagnosed-by-doctor_No_2_0': 536,
        'Glasses-wornrequired-right_wearing_0_0': 537, 'Glasses-wornrequired-left_wearing_0_0': 538,
        'Father-still-alive_No_2_0': 539, 'Other-serious-medical-conditiondisability-diagnosed-by-doctor_No_2_0': 540,
        'Smokingsmokers-in-household_Yes-one-household-member-smokes_0_0': 541,
        'Frequency-of-stair-climbing-in-last-4-weeks_1620-times-a-day_0_0': 542,
        'Stiffness-method_Direct-entry_2_0': 543, 'Workplace-very-noisy_Sometimes_0_0': 544,
        'Frequency-of-stair-climbing-in-last-4-weeks_None_0_0': 545,
        'Duration-of-other-exercises_Between-15-and-30-minutes_0_0': 546,
        'Which-eyes-affected-by-myopia-short-sight_Both-eyes_0_0': 547,
        'Operator-indicated-brain-MRI-measurement-completed_yes_2_0': 548, 'Digits-entered-correctly_yes_0_3': 549,
        'Leg-pain-on-walking_No_2_0': 550, 'Worked-with-materials-containing-asbestos_Rarelynever_0_3': 551,
        'Nonbutter-spread-type-details_Flora-ProActive-or-Benecol_0_0': 552, 'Noisy-workplace_No_2_0': 553,
        'Falls-in-the-last-year_No-falls_2_0': 554, 'Workplace-full-of-chemical-or-other-fumes_Rarelynever_0_3': 555,
        'Operation-code_tonsillectomy-adenoids_0_0': 556, 'Eye-problemsdisorders_None-of-the-above_2_0': 557,
        'composite_cad_dcm_hcm_hf_mi': 558, 'Pain-types-experienced-in-last-month_Neck-or-shoulder-pain_0_1': 559,
        'Other-eye-problems_No_2_0': 560, 'Cheese-intake_56-times-a-week_0_0': 561,
        'Country-of-birth-UKelsewhere_Elsewhere_0_0': 562, 'Current-tobacco-smoking_Yes-on-most-or-all-days_0_0': 563,
        'Country-of-birth-UKelsewhere_Scotland_0_0': 564, 'Vicorder-results-plausible_Yes_2_0': 565,
        'Duration-of-light-DIY_Between-1-and-15-hours_0_0': 566, 'Abdominal-MRI-measurement-completed_Yes_2_0': 567,
        'Leg-pain-on-walking_Yes_0_0': 568, 'Prospective-memory-result_Correct-recall-on-first-attempt_2_0': 569,
        'PM-initial-answer_Orange-circle_2_0': 570, 'Variation-in-diet_Often_0_0': 571,
        'Which-eyes-affected-by-presbyopia_Both-eyes_0_0': 572, 'FI4-positional-arithmetic_6_2_0': 573,
        'Cancer-diagnosed-by-doctor_Yes-you-will-be-asked-about-this-later-by-an-interviewer_0_0': 574,
        'Types-of-transport-used-excluding-work_Carmotor-vehicle_2_0': 575,
        'Types-of-physical-activity-in-last-4-weeks_Walking-for-pleasure-not-as-a-means-of-transport_2_0': 576,
        'Usual-walking-pace_Slow-pace_0_0': 577, 'Wheeze-or-whistling-in-the-chest-in-last-year_No_2_0': 578,
        'Back-pain-for-3-months_No_0_0': 579,
        'Frequency-of-walking-for-pleasure-in-last-4-weeks_45-times-a-week_0_0': 580,
        'Neckshoulder-pain-for-3-months_No_0_0': 581, 'Gap-coding_Retired_0_0': 582,
        'Never-eat-eggs-dairy-wheat-sugar_I-eat-all-of-the-above_2_0': 583, 'PM-initial-answer_Blue-square_0_0': 584,
        'Surgeryamputation-of-toe-or-leg_No_0_0': 585, 'Alcohol-intake-frequency_Never_0_0': 586,
        'Mineral-and-other-dietary-supplements_Glucosamine_0_0': 587, 'diabetes_type_2': 588,
        'Illnesses-of-father_Do-not-know-group-2_0_1': 589,
        'Qualifications_Other-professional-qualifications-eg-nursing-teaching_0_1': 590,
        'Triplet-correct-right_yes_2_2': 591, 'Fractured-heel-right_no_2_0': 592, 'imaging_thoracic': 593,
        'coronary_artery_disease_hard': 594,
        'Own-or-rent-accommodation-lived-in_Own-outright-by-you-or-someone-in-your-household_2_0': 595,
        'Fractured-heel-left_no_2_0': 596, 'Workplace-very-dusty_Rarelynever_0_3': 597,
        'Surgery-on-leg-arteries-other-than-for-varicose-veins_No_0_0': 598,
        'Duration-of-heavy-DIY_Between-15-and-30-minutes_0_0': 599, 'Digits-entered-correctly_yes_0_4': 600,
        'Caffeine-drink-within-last-hour_No_2_0': 601,
        'Workplace-had-a-lot-of-cigarette-smoke-from-other-people-smoking_Rarelynever_0_3': 602,
        'Contraindications-for-spirometry_Yes_0_0': 603, 'Noncancer-illness-code-selfreported_asthma_0_0': 604,
        'Triplet-correct-left_yes_2_2': 605,
        'Types-of-physical-activity-in-last-4-weeks_Light-DIY-eg-pruning-watering-the-lawn_0_0': 606,
        'Duration-walking-for-pleasure_Between-15-and-2-hours_0_0': 607, 'Illnesses-of-father_Prostate-cancer_0_0': 608,
        'allergic_rhinitis': 609, 'hypothyroidism': 610, 'Illnesses-of-father_Diabetes_0_0': 611,
    },
)
