name: Test ml4h Python package

on:
  workflow_dispatch:
  push:
    branches: [ rr_test ]
  pull_request:
    branches: [ rr_test ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11, 3.12]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        #pip cache purge
        python -m pip install --upgrade pip
        #python -m pip install --upgrade pip setuptools wheel "cython<3.0.0"
        # pip install "PyYAML==6.0.1" --only-binary=PyYAML --no-build-isolation
        # Install the ml4h Python package.
        pip install .
    - name: Test with pytest and pytest-xdist
      run: |
        pytest tests -m "not slow" -n auto
